parallel -j 4 < /data/bioit/biodata/zenghp/bin/ctDNA_dev/cfBEST/cfBEST-pipeline/example/outdir/detect.sh
perl /data/bioit/biodata/zenghp/bin/ctDNA_dev/cfBEST/cfBEST-pipeline/get_hotspot_detect.pl -id /data/bioit/biodata/zenghp/bin/ctDNA_dev/cfBEST/cfBEST-pipeline/example/outdir/05.variant_detect/variants/ -is /data/bioit/biodata/zenghp/bin/ctDNA_dev/cfBEST/cfBEST-pipeline/example/demo.config -ic config/panel.config -cid AB-10  -k Total -od /data/bioit/biodata/zenghp/bin/ctDNA_dev/cfBEST/cfBEST-pipeline/example/outdir/statistic
perl /data/bioit/biodata/zenghp/bin/ctDNA_dev/cfBEST/cfBEST-pipeline/tma_genotyping/cffdna_estimation_and_fetal_genotyping.pl -i /data/bioit/biodata/zenghp/bin/ctDNA_dev/cfBEST/cfBEST-pipeline/example/demo.config -ic config/panel.config -cid AB-10 -id /data/bioit/biodata/zenghp/bin/ctDNA_dev/cfBEST/cfBEST-pipeline/example/outdir/statistic/05.hotspots_result/ -k Total -od /data/bioit/biodata/zenghp/bin/ctDNA_dev/cfBEST/cfBEST-pipeline/example/outdir/06.genotyping -e -d 50
perl /data/bioit/biodata/zenghp/bin/ctDNA_dev/cfBEST/cfBEST-pipeline/merge_stat_result.pl -id /data/bioit/biodata/zenghp/bin/ctDNA_dev/cfBEST/cfBEST-pipeline/example/outdir/01.fastq_uniq/ --Uniq_QC -od /data/bioit/biodata/zenghp/bin/ctDNA_dev/cfBEST/cfBEST-pipeline/example/outdir/statistic
perl /data/bioit/biodata/zenghp/bin/ctDNA_dev/cfBEST/cfBEST-pipeline/merge_stat_result.pl -id /data/bioit/biodata/zenghp/bin/ctDNA_dev/cfBEST/cfBEST-pipeline/example/outdir/02.barcode_process/ --Bar_QC -od /data/bioit/biodata/zenghp/bin/ctDNA_dev/cfBEST/cfBEST-pipeline/example/outdir/statistic
perl /data/bioit/biodata/zenghp/bin/ctDNA_dev/cfBEST/cfBEST-pipeline/merge_stat_result.pl -id /data/bioit/biodata/zenghp/bin/ctDNA_dev/cfBEST/cfBEST-pipeline/example/outdir/03.data_process/ --Primer_QC -od /data/bioit/biodata/zenghp/bin/ctDNA_dev/cfBEST/cfBEST-pipeline/example/outdir/statistic
perl /data/bioit/biodata/zenghp/bin/ctDNA_dev/cfBEST/cfBEST-pipeline/merge_stat_result.pl -id /data/bioit/biodata/zenghp/bin/ctDNA_dev/cfBEST/cfBEST-pipeline/example/outdir/04.consensus_make/ --Map_QC -od /data/bioit/biodata/zenghp/bin/ctDNA_dev/cfBEST/cfBEST-pipeline/example/outdir/statistic
perl /data/bioit/biodata/zenghp/bin/ctDNA_dev/cfBEST/cfBEST-pipeline/merge_stat_result.pl -id /data/bioit/biodata/zenghp/bin/ctDNA_dev/cfBEST/cfBEST-pipeline/example/outdir/04.consensus_make/ --Consens_Stat -od /data/bioit/biodata/zenghp/bin/ctDNA_dev/cfBEST/cfBEST-pipeline/example/outdir/statistic
perl /data/bioit/biodata/zenghp/bin/ctDNA_dev/cfBEST/cfBEST-pipeline/merge_stat_result.pl -id /data/bioit/biodata/zenghp/bin/ctDNA_dev/cfBEST/cfBEST-pipeline/example/outdir/05.variant_detect/ --HotSpot_Stat -od /data/bioit/biodata/zenghp/bin/ctDNA_dev/cfBEST/cfBEST-pipeline/example/outdir/statistic
perl /data/bioit/biodata/zenghp/bin/ctDNA_dev/cfBEST/cfBEST-pipeline/merge_stat_result.pl -id /data/bioit/biodata/zenghp/bin/ctDNA_dev/cfBEST/cfBEST-pipeline/example/outdir/05.variant_detect/ --Variant_Known -od /data/bioit/biodata/zenghp/bin/ctDNA_dev/cfBEST/cfBEST-pipeline/example/outdir/statistic
perl /data/bioit/biodata/zenghp/bin/ctDNA_dev/cfBEST/cfBEST-pipeline/merge_total_statistics.pl -id /data/bioit/biodata/zenghp/bin/ctDNA_dev/cfBEST/cfBEST-pipeline/example/outdir -k Total -od /data/bioit/biodata/zenghp/bin/ctDNA_dev/cfBEST/cfBEST-pipeline/example/outdir/statistic
cp /data/bioit/biodata/zenghp/bin/ctDNA_dev/cfBEST/cfBEST-pipeline/example/outdir/06.genotyping/Total.genotype.result /data/bioit/biodata/zenghp/bin/ctDNA_dev/cfBEST/cfBEST-pipeline/example/outdir/statistic
cp /data/bioit/biodata/zenghp/bin/ctDNA_dev/cfBEST/cfBEST-pipeline/example/outdir/06.genotyping/cffdna.txt /data/bioit/biodata/zenghp/bin/ctDNA_dev/cfBEST/cfBEST-pipeline/example/outdir/statistic/Total.cffdna.txt
cp /data/bioit/biodata/zenghp/bin/ctDNA_dev/cfBEST/cfBEST-pipeline/example/outdir/06.genotyping/*.genotype.txt /data/bioit/biodata/zenghp/bin/ctDNA_dev/cfBEST/cfBEST-pipeline/example/outdir/statistic/06.genotype_result//
